### ISSUE TITLE
Upgrading Issue (resolved for now)

### ISSUE THREAD

**Issue by Zogproof** [johna23-lab/F-Void#1]
Hi johna23-lab.

 Just wanted to explain an issue I've had, and what I've done to resolve it for now.

 I recently installed  F-Void on a USB drive. Calamares is still available on a USB drive install via Menu>System Tools>Install System - very useful!

 I did have some trouble running "sudo xbps-install -Syu" on the USB install. I was getting things like "amule-git : broken, unresolvable shlib `libicu.so'"

 My solution at the moment is:

 sudo xbps-remove -y amule wxhexditor
 sudo xbps-pkgdb -m hold boost-python3

 (I worked out that boost-python3 (version 1.82) and the other two "packages"  are basically dependencies  for Calamares, and the xbps command was trying to upgrade boost-python3  from version 1.82 to version 1.83. I'm not sure what is happening with the amule, wxhexditor and boost-python3 "packages," because they don't show as being installed in OctoXBPS etc.. I imagine Calamares was compiled as such).

 The second line isn't needed for Hard drive/partition installs because Calamares is no longer present in that case as far as I can tell.

 Hope the info helps.

 Regards,

 Zogproof

**Comment by Zogproof** [comment]
Update: Looks like holding boost-python3  is now causing problems for libpeas, libmobiledevice, and  remmina (on the USB install) . So I'd have to uninstall Calamares on the USB install to be able to upgrade it I guess ...

**Comment by johna23-lab** [comment]
Thanks for commenting, Void Linux had a bit issue with python3, i'm aware with the bugs of Amule and wxeditor, need to rebuild new packages, i expect to release a new iso before November (2023) ends

**Comment by Zogproof** [comment]
All good- closing.
